# Generated by Django 3.2 on 2021-04-29 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('fechaPago', models.DateField()),
                ('documentoIdentificacionArrendatario', models.IntegerField(primary_key=True, serialize=False)),
                ('codigoInmueble', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('valorPagado', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
    ]
